### ISSUE TITLE
assert helpers are now missing

### ISSUE THREAD

**Issue by sugendran** [pdiemert/ssa#4]
Error: Cannot find module '../modules/assert-extras'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/sugendranganess/Documents/git/mm.node.api/node_modules/ssa/lib/index.js:6:13)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)

**Comment by sugendran** [comment]
it looks like npm didn't expand your submodules in git. Why not just make the npm dependancies?

**Comment by pdiemert** [comment]
Fixed in 0.1.6
